In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

# Create data that produces the expected output
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], 
              [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]])
y = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

print("X_train:")
print(X_train)
print("\ny_train:")
print(y_train)
print("\nX_test:")
print(X_test)
print("\ny_test:")
print(y_test)


X_train:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]

y_train:
[1 2 3 4 5 6 7 8]

X_test:
[[17 18]
 [19 20]]

y_test:
[ 9 10]
